# Generated by Django 3.2 on 2021-04-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Tech Coach'), (2, 'Academic Coach'), (3, 'Talent Placement Coach')])),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
